language: scala
jdk: oraclejdk8

scala:
   - 2.12.2

script:
   - sbt ++$TRAVIS_SCALA_VERSION clean
   # build and run tests
   - sbt test:compile
   - CP=$(sbt ++$TRAVIS_SCALA_VERSION "export test:dependency-classpath" --error)
   - java -cp "$CP" org.scalatest.tools.Runner -R target/scala-2.12/test-classes -o -PS3
   # build optimized JavaScript version (env/web)
   - sbt ++$TRAVIS_SCALA_VERSION fullOptJS
   # avoid unnecessary cache updates, source: http://www.scala-sbt.org/0.13/docs/Travis-CI-with-sbt.html
   - find $HOME/.sbt -name "*.lock" | xargs rm
   - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

cache:
   directories:
      - $HOME/.ivy2/cache
      - $HOME/.sbt/boot/
   
install:
   - . $HOME/.nvm/nvm.sh
   - nvm install stable
   - nvm use stable
   - npm install
   - npm install jsdom
  
