language: scala
jdk: oraclejdk8

scala:
   - 2.12.2

script:
   - sbt clean test
   
install:
   - . $HOME/.nvm/nvm.sh
   - nvm install stable
   - nvm use stable
   - npm install
   - npm install jsdom
  
